// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatziEntityFramework;

#nullable disable

namespace PlatziEntityFramework.Migrations
{
    [DbContext(typeof(WorkContext))]
    [Migration("20230825005155_NewDatatoWorks")]
    partial class NewDatatoWorks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatziEntityFramework.Model.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Weigth")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06b0"),
                            Name = "Actividades Pendientes",
                            Weigth = 20
                        },
                        new
                        {
                            CategoryID = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06b1"),
                            Name = "Actividades Personales",
                            Weigth = 50
                        });
                });

            modelBuilder.Entity("PlatziEntityFramework.Model.Work", b =>
                {
                    b.Property<Guid>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("comentary")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("WorkId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Work", (string)null);

                    b.HasData(
                        new
                        {
                            WorkId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06c0"),
                            CategoryId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06b0"),
                            DateCreate = new DateTime(2023, 8, 24, 19, 51, 55, 661, DateTimeKind.Local).AddTicks(1544),
                            Priority = 1,
                            Title = "Pago de Servicios Publicos"
                        },
                        new
                        {
                            WorkId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06c1"),
                            CategoryId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06b1"),
                            DateCreate = new DateTime(2023, 8, 24, 19, 51, 55, 661, DateTimeKind.Local).AddTicks(1556),
                            Priority = 0,
                            Title = "terminar de ver pelicula en netflix"
                        },
                        new
                        {
                            WorkId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06c2"),
                            CategoryId = new Guid("32a46c4e-e2f2-4b0c-9fc1-cf0f4cbe06b1"),
                            DateCreate = new DateTime(2023, 8, 24, 19, 51, 55, 661, DateTimeKind.Local).AddTicks(1559),
                            Priority = 2,
                            Title = "Dar examenes de devsu antes del domingo"
                        });
                });

            modelBuilder.Entity("PlatziEntityFramework.Model.Work", b =>
                {
                    b.HasOne("PlatziEntityFramework.Model.Category", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlatziEntityFramework.Model.Category", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
